#!/usr/bin/env python3
"""
katana_sbol.py — export a Katana build as SBOL 3.

Why this module exists, beyond "SBOL is a standard we should support":

Katana's whole claim is that a construct is not a file you trust but a thing you can
re-derive and check — every base traces to a sealed part, and every part traces to a
primary source. SBOL 3 is built on RDF and carries PROV-O, so `wasDerivedFrom` is a
first-class edge in the data model. That means our provenance is not squeezed into a
free-text note; it serialises natively, and a tool that has never heard of Katana can
still follow a part back to its accession.

Two deliberate choices:

  * SEQUENCES ARE EMITTED UPPERCASE — the engine's canonical form. `seq_sha256` is
    computed over the uppercased sequence, so you can recompute our hash directly
    from the SBOL file and get the same answer. Round-tripping through SBOL does not
    break hash verification, which would defeat the point of publishing it.

  * IDENTIFIERS ARE SANITISED, NOT RENAMED — SBOL display_ids must match
    ^[a-zA-Z_][a-zA-Z0-9_]*$, and real part names contain '-' and '.'
    (HrpR.Ec-opt, pAP-Logic, P_hrpL). Those characters become '_', and the original
    id is preserved verbatim in the SBOL `name` field. Nothing is silently lost.

This is an OPTIONAL exporter. The engine core stays near-stdlib; if `sbol3` is not
installed the caller is told loudly and the build continues without SBOL — the same
fail-loud-not-silent rule the dry-lab gate follows.

Usage (via the engine):   python katana_build.py <spec> --sbol out.ttl
Standalone:               imported by katana_build.py; not a CLI on its own.
"""
from __future__ import annotations

import re
from pathlib import Path

# Sequence Ontology terms. sbol3 exposes the common ones as constants; origin of
# replication is not among them, so it is written out in the same identifiers.org
# form the library itself uses (cf. SBO_DNA = https://identifiers.org/SBO:0000251).
SO_ORIGIN_OF_REPLICATION = "https://identifiers.org/SO:0000296"

FORMATS = {
    "turtle": "ttl",
    "ttl": "ttl",
    "nt": "nt",
    "ntriples": "nt",
    "jsonld": "jsonld",
    "rdfxml": "xml",
}


def _sanitise(part_id: str) -> str:
    """Make an SBOL-legal display_id, preserving the original in `name`.

    SBOL 3 requires ^[a-zA-Z_][a-zA-Z0-9_]*$. Part ids in the wild contain '-' and
    '.', so those map to '_'. A leading digit gets an underscore prefix.
    """
    s = re.sub(r"[^A-Za-z0-9_]", "_", part_id)
    if not s or not re.match(r"^[A-Za-z_]", s):
        s = "_" + s
    return s


def _role_for(role: str, sbol3) -> str:
    return {
        "promoter": sbol3.SO_PROMOTER,
        "rbs": sbol3.SO_RBS,
        "cds": sbol3.SO_CDS,
        "reporter": sbol3.SO_CDS,
        "marker": sbol3.SO_CDS,
        "terminator": sbol3.SO_TERMINATOR,
        "ori": SO_ORIGIN_OF_REPLICATION,
    }.get(str(role).lower(), sbol3.SO_ENGINEERED_REGION)


def _source_uri(src: dict) -> str | None:
    """Resolve a part's primary source to a dereferenceable URI, for wasDerivedFrom.

    This is the edge that makes the provenance machine-followable: a consumer can
    take the SBOL and go straight to the record the sequence came from.
    """
    if not src:
        return None
    if "registry" in src or "part" in src:
        part = src.get("part") or src.get("registry")
        if part:
            return f"https://parts.igem.org/Part:{part}"
    acc = src.get("accession")
    if acc:
        return f"https://identifiers.org/nucleotide:{acc}"
    return None


def _provenance_note(pid: str, src: dict, design: dict, sha: str) -> str:
    """Human-readable provenance, mirroring what LOCK.tsv records.

    Every key is emitted generically rather than cherry-picked: source records in the
    wild carry different shapes (registry+part, db+accession+coords+strand, db+ucf+ref
    for a Cello UCF terminator, db+plasmid). Hand-picking three keys silently drops the
    provenance of everything shaped differently.
    """
    bits = [f"Katana sealed part '{pid}'", f"seq_sha256={sha}"]
    if src:
        bits.append("source: " + ", ".join(f"{k}={v}" for k, v in src.items() if v not in (None, "")))
        if src.get("coords"):
            bits.append("coords are 1-based inclusive (GenBank convention)")
    if design:
        bits.append("design_record: " + ", ".join(f"{k}={v}" for k, v in design.items() if v not in (None, "")))
    return "; ".join(bits)


def _design_activity(pid: str, disp: str, design: dict, doc, sbol3, agents: dict):
    """Model a DESIGNED part as PROV: it was *generated by* a computational activity.

    A codon-optimised CDS or an OSTIR-tuned RBS has no accession to point at — it was
    computed. `wasDerivedFrom` would be a lie there; `wasGeneratedBy` an Activity, with
    the design tool as the associated Agent, is what actually happened. Reference parts
    and designed parts therefore carry *different* provenance edges, which is the whole
    distinction Katana's part classes encode.
    """
    tool = str(design.get("tool") or design.get("engine") or "unspecified-tool")
    agent_id = _sanitise(f"agent_{tool}")
    agent = agents.get(agent_id)
    if agent is None:
        agent = sbol3.Agent(agent_id)
        agent.name = tool
        doc.add(agent)
        agents[agent_id] = agent

    activity = sbol3.Activity(f"{disp}_design", types=[sbol3.SBOL_DESIGN])
    activity.name = f"design of {pid}"
    activity.description = ", ".join(f"{k}={v}" for k, v in design.items() if v not in (None, ""))
    assoc = sbol3.Association(agent=agent.identity, roles=[sbol3.SBOL_DESIGN])
    activity.association.append(assoc)
    doc.add(activity)
    return activity


def export_sbol(spec: dict, resolved: dict, insert_seq: str, features: list,
                out_path: Path, namespace: str = "https://igem.org/katana",
                fmt: str = "turtle", validate: bool = True) -> tuple[bool, list[str]]:
    """Write the build as SBOL 3. Returns (ok, messages).

    ok=False means SBOL was NOT written (missing library, or validation failed).
    The caller is expected to surface every message rather than swallow it.
    """
    msgs: list[str] = []
    try:
        import sbol3
    except ImportError:
        return False, ["WARN SBOL: sbol3 not installed — SBOL export SKIPPED, not enforced "
                       "this run (py -m pip install sbol3)."]

    fmt_key = str(fmt).lower()
    if fmt_key not in FORMATS:
        return False, [f"BLOCK SBOL: unknown format '{fmt}' (choose: {', '.join(sorted(set(FORMATS)))})"]

    sbol3.set_namespace(namespace)
    doc = sbol3.Document()

    sid = str(spec.get("id", "construct"))
    version = spec.get("version", 1)
    spec_parts = {p["id"]: p for p in spec.get("parts", [])}

    # ── one Component + Sequence per distinct sealed part ───────────────────
    part_components: dict[str, object] = {}
    agents: dict[str, object] = {}
    n_derived = n_generated = 0
    order = spec.get("architecture", {}).get("order", [])
    for pid in dict.fromkeys(order):          # distinct, order-preserving
        if pid not in resolved:
            continue
        data = resolved[pid]
        disp = _sanitise(pid)
        meta = spec_parts.get(pid, {})
        src = meta.get("source", {}) or {}
        design = meta.get("design_record", {}) or {}

        # Uppercase: the engine's canonical form, so seq_sha256 recomputes from this file.
        seq_obj = sbol3.Sequence(f"{disp}_sequence",
                                 elements=data["seq"].upper(),
                                 encoding=sbol3.IUPAC_DNA_ENCODING)
        seq_obj.name = f"{pid} sequence"
        doc.add(seq_obj)

        comp = sbol3.Component(disp, sbol3.SBO_DNA,
                               roles=[_role_for(meta.get("role", ""), sbol3)],
                               sequences=[seq_obj.identity])
        comp.name = pid                                   # original id, verbatim
        comp.description = _provenance_note(pid, src, design, data["seq_sha256"])

        # PROV-O, and the two cases are genuinely different:
        #   reference part -> wasDerivedFrom the primary record it was fetched from
        #   designed part  -> wasGeneratedBy the computation that produced it
        uri = _source_uri(src)
        if uri and hasattr(comp, "derived_from"):
            comp.derived_from = [uri]
            n_derived += 1
        elif design:
            activity = _design_activity(pid, disp, design, doc, sbol3, agents)
            comp.generated_by = [activity.identity]
            n_generated += 1
        doc.add(comp)
        part_components[pid] = comp

    if not part_components:
        return False, ["BLOCK SBOL: no resolved parts to export"]

    # ── the construct itself ────────────────────────────────────────────────
    c_disp = _sanitise(f"{sid}_insert_v{version}")
    c_seq = sbol3.Sequence(f"{c_disp}_sequence",
                           elements=insert_seq.upper(),
                           encoding=sbol3.IUPAC_DNA_ENCODING)
    c_seq.name = f"{sid} insert sequence"
    doc.add(c_seq)

    construct = sbol3.Component(c_disp, sbol3.SBO_DNA,
                                roles=[sbol3.SO_ENGINEERED_REGION],
                                sequences=[c_seq.identity])
    construct.name = f"{sid} insert v{version}"
    construct.description = (
        f"Katana deterministic build of {sid} v{version}: {len(insert_seq)} bp, assembled "
        f"from {len(part_components)} sealed parts. Regenerable: the same Spec and the same "
        f"sealed Parts Library reproduce this sequence byte-for-byte. Sequences are uppercase "
        f"so seq_sha256 can be recomputed directly from this document.")

    # SubComponents follow architecture.order, so a part used twice appears twice.
    subs = []
    for idx, pid in enumerate(order):
        if pid not in part_components:
            continue
        sub = sbol3.SubComponent(part_components[pid])
        sub.name = f"{pid} @{idx + 1}"
        construct.features.append(sub)
        subs.append(sub)

    # Adjacency: 'meets' says these are contiguous, which is what a built cassette is.
    for a, b in zip(subs, subs[1:]):
        construct.constraints.append(
            sbol3.Constraint(sbol3.SBOL_MEETS, a, b))

    doc.add(construct)

    # ── validate before claiming this is SBOL ───────────────────────────────
    if validate:
        report = doc.validate()
        errors = list(getattr(report, "errors", []) or [])
        warnings = list(getattr(report, "warnings", []) or [])
        if errors:
            msgs.append(f"BLOCK SBOL: document failed validation with {len(errors)} error(s):")
            for e in errors[:5]:
                msgs.append(f"    {e}")
            return False, msgs
        if warnings:
            msgs.append(f"INFO SBOL: {len(warnings)} validation warning(s) (non-fatal).")

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    # Serialise to a string and write the bytes ourselves as UTF-8.
    #
    # Not paranoia: Document.write() writes through the platform default encoding, so on
    # a cp1252 Windows box a single non-ASCII character in any name or description
    # produces a file that is NOT valid UTF-8 — and RDF/Turtle must be UTF-8. It parses
    # fine locally and fails for everyone else, which is the worst kind of bug to ship.
    # (Found exactly that way: one em dash in this module's own description text.)
    payload = doc.write_string(FORMATS[fmt_key])
    out_path.write_bytes(payload.encode("utf-8"))

    # Verify the artifact, not the tool: re-read the bytes and prove they are UTF-8.
    try:
        out_path.read_bytes().decode("utf-8")
    except UnicodeDecodeError as e:
        return False, msgs + [f"BLOCK SBOL: written file is not valid UTF-8 ({e}) — refusing "
                              f"to claim SBOL output."]

    msgs.append(f"INFO SBOL: validated SBOL 3 written -> {out_path}")
    msgs.append(f"INFO SBOL: {len(part_components)} part Components + 1 construct "
                f"({len(subs)} SubComponents, {max(len(subs) - 1, 0)} adjacency constraints).")
    msgs.append(f"INFO SBOL: provenance — {n_derived} wasDerivedFrom (reference parts), "
                f"{n_generated} wasGeneratedBy (designed parts, {len(agents)} tool Agent(s)).")
    return True, msgs
