#!/usr/bin/env python3
"""web_deploy.py — assemble the static site and, on request, publish it.

`katana deploy` lands here.

The published site is not just `ui/web/`. Pyodide fetches the engine modules and the
reference set over HTTP, so the deployable artifact is a staging directory holding the
page plus `core/`, the audit half of `kagami/`, the reference set and the bundled genome.
This script assembles exactly the file list `web_serve.SERVE` names, so the published
site and the local server can never be serving different things -- which is the whole
point: a published page that is a hand-assembled variant of the engine is the same defect
as a construct assembled by hand.

By default it only STAGES, and prints what it would publish. Publishing is an outward
action that needs saying out loud, so it takes --push and a remote.

The iGEM GitLab project is never pushed to by this script. The only sanctioned outward
destination is the separate GitHub repository the team chose for the web test.
"""
import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

DEFAULT_REMOTE = "https://github.com/andrewhao66/iGEM-katana-webtest.git"

# Where each served file lands in the published site. The page is served from the root,
# so index.html and index.js move up out of ui/web/; everything else keeps its path,
# because that is what the page's own fetches expect.
def published_path(rel):
    if rel == "ui/web/index.html":
        return "index.html"
    if rel == "ui/web/index.js":
        return "index.js"
    return rel


NOJEKYLL = (
    "# GitHub Pages runs Jekyll by default, which SKIPS files and directories whose\n"
    "# names begin with an underscore. Nothing here starts with one today, but the\n"
    "# engine vendors _vendor/ and a future page file could, and a silently missing\n"
    "# module would read as a broken page rather than a missing file. Disable it.\n"
)

README = """# Katana — check a sequence, in your browser

This is the published build of Katana's sequence auditor. Open the page and drop a
GenBank, FASTA or spreadsheet file on it.

**Nothing is uploaded.** The page runs Katana's own audit modules through Pyodide —
CPython compiled to WebAssembly — so the sequence you check never leaves your machine.

It is not a reimplementation. The `.py` files here are the same ones the command-line
tool runs; two implementations of one check drift apart, and that drift is the failure
the project exists to prevent.

## What it does and does not do

It identifies the parts in a sequence against {nrefs} public references and reports what
it finds: a label that disagrees with its bases, a truncated part, a broken reading
frame, restriction sites that matter for your assembly method, GC and homopolymer
outliers, direct repeats, host homology, and size against a vendor cap.

It does **not** seal parts or build constructs. Those need a parts library that lives in
git, with a history you can audit — so they belong to the command-line tool.

## Source

Generated by `web_deploy.py` from the Katana bundle. Do not edit these files here: edit
them in the bundle and re-run the deploy, or the published page becomes a hand-assembled
variant of the engine, which is exactly what this project refuses to allow for DNA.
"""


def stage(target):
    """Copy the deployable file set into `target`. Returns (files, bytes)."""
    sys.path.insert(0, HERE)
    import web_serve

    missing = web_serve.missing_files()
    if missing:
        raise SystemExit("BLOCK: these files are missing, so the site would be "
                         "incomplete:\n  " + "\n  ".join(missing))

    if os.path.isdir(target):
        shutil.rmtree(target)
    os.makedirs(target)

    total = 0
    files = []
    for rel in web_serve.SERVE:
        dest = os.path.join(target, published_path(rel))
        os.makedirs(os.path.dirname(dest) or target, exist_ok=True)
        shutil.copyfile(os.path.join(HERE, rel), dest)
        size = os.path.getsize(dest)
        total += size
        files.append((published_path(rel), size))

    with open(os.path.join(target, ".nojekyll"), "w", encoding="utf-8") as f:
        f.write(NOJEKYLL)

    nrefs = "?"
    try:
        with open(os.path.join(target, "kagami", "refs", "reference_parts.fasta"),
                  encoding="utf-8") as f:
            nrefs = "{:,}".format(sum(1 for ln in f if ln.startswith(">")))
    except Exception:
        pass
    with open(os.path.join(target, "README.md"), "w", encoding="utf-8") as f:
        f.write(README.format(nrefs=nrefs))

    return files, total


def publish(target, remote, branch="main"):
    """Commit the staged site and push it. Outward-facing; only called with --push."""
    def git(*args):
        p = subprocess.run(["git"] + list(args), cwd=target,
                           capture_output=True, text=True)
        if p.returncode != 0:
            raise SystemExit("BLOCK: git %s failed:\n%s"
                             % (" ".join(args), (p.stdout + p.stderr).strip()))
        return p.stdout

    git("init", "-q", "-b", branch)
    git("add", "-A")
    git("-c", "user.name=katana-deploy",
        "-c", "user.email=katana-deploy@localhost",
        "commit", "-q", "-m",
        "Publish Katana web auditor\n\n"
        "Generated by web_deploy.py from the Katana bundle. The .py files here are the\n"
        "engine's own modules, not a reimplementation.")
    git("remote", "add", "origin", remote)
    # Force, because this is a generated artifact: its history is the bundle's history,
    # and a published site that has diverged from the bundle is the defect, not a
    # change worth preserving.
    git("push", "--force", "origin", branch)
    return 0


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    target = os.path.join(HERE, "_site")
    remote = DEFAULT_REMOTE
    do_push = False
    for i, tok in enumerate(argv):
        if tok == "--out" and i + 1 < len(argv):
            target = os.path.abspath(argv[i + 1])
        elif tok == "--remote" and i + 1 < len(argv):
            remote = argv[i + 1]
        elif tok == "--push":
            do_push = True

    files, total = stage(target)
    print("Staged the site in %s" % target)
    print()
    for rel, size in files:
        print("  %-44s %8.1f KB" % (rel, size / 1024.0))
    print("  %-44s %8.1f KB" % ("(total)", total / 1024.0))
    print()
    print("First load is about %.1f MB uncompressed; a web server gzips the sequence"
          % (total / 1e6))
    print("data to roughly a quarter of that, and the browser caches it.")
    print()
    if not do_push:
        print("Nothing was published. To publish this to")
        print("    %s" % remote)
        print("run the same command with --push.")
        print()
        print("To see it locally first, with no publishing at all:  ./katana web")
        return 0

    print("Publishing to %s ..." % remote)
    rc = publish(target, remote)
    if rc == 0:
        print("Pushed. GitHub Pages serves it once the repository's Pages setting")
        print("points at the branch -- Settings -> Pages -> Deploy from a branch.")
    return rc


if __name__ == "__main__":
    sys.exit(main())
