"""
kg_refs.py — Kagami reference part set (PUBLIC parts only).

The set is loaded from a bundled data file (refs/reference_parts.tsv +
reference_parts.fasta), which is generated by build_refs.py — mostly a projection
of the *verified, sealed* public reference parts in the Synbio parts-library, plus
a few hand-seeded canonical parts. Each entry carries a `provenance` string:
  - "parts-library <source>"  → sequence came from a sealed, LOCK-verified library
    part (primary-sourced, hash-checked). Trustworthy.
  - "seed — verify vs ..."     → hand-seeded canonical public sequence still to be
    confirmed against its primary source. Kagami surfaces this tag.

IP boundary: PUBLIC reference parts only (Anderson promoters, standard RBS/
terminators, common reporters/markers/oris, public inducible promoters). No
`designed` or otherwise non-public sequences are included. Kagami ships under the
WIST iGEM team on this basis. To expand, re-run build_refs.py (never paste a
sequence out of a construct you are auditing — circular provenance).
"""
import os

_DIR = os.path.dirname(os.path.abspath(__file__))
_FASTA = os.path.join(_DIR, "refs", "reference_parts.fasta")
_TSV = os.path.join(_DIR, "refs", "reference_parts.tsv")
_GENOMES = os.path.join(_DIR, "genomes")

STRENGTH_ORDER = {"weak": 1, "medium": 2, "strong": 3}

# Host chassis for the >40 bp off-target / recombination-substrate check. Each maps to a bundled
# genome FASTA and a recA status. recA decides SEVERITY, not presence (see kg_audit): a host match
# is a recombination substrate only in a recA+ background. K-12 derivatives share essentially the
# same chromosome, so DH5alpha and MG1655 point at the same genome and differ only in recA — which
# is exactly the distinction that matters for a student cloning a plasmid before moving it to a
# chassis. Ordered; the GUI adds a "No host / skip" entry ahead of these.
HOSTS = [
    ("E. coli K-12 MG1655 (recA+, the chassis)",
     dict(file="MG1655_ecoli_NC_000913.3.fna", reca=True)),
    ("E. coli cloning strain — DH5α / Top10 (recA−)",
     dict(file="MG1655_ecoli_NC_000913.3.fna", reca=False)),
]


def host_genome_path(fname):
    """Absolute path to a bundled host genome, or None if it is not present."""
    p = os.path.join(_GENOMES, fname)
    return p if os.path.isfile(p) else None

# Minimal built-in fallback so the tool still runs if the data file is absent.
_FALLBACK = [
    dict(id="B0032", registry="BBa_B0032", name="RBS (weak)", role="rbs",
         variant="weak", seq="TCACACAGGAAAG", provenance="seed — verify vs Registry"),
    dict(id="B0034", registry="BBa_B0034", name="RBS (strong)", role="rbs",
         variant="strong", seq="AAAGAGGAGAAA", provenance="seed — verify vs Registry"),
    dict(id="J23116", registry="BBa_J23116", name="Anderson promoter (weak)",
         role="promoter", variant="constitutive-weak",
         seq="TTGACAGCTAGCTCAGTCCTAGGGACTATGCTAGC",
         provenance="seed — verify vs Registry"),
    dict(id="B0015", registry="BBa_B0015", name="Double terminator", role="terminator",
         variant="double",
         seq=("CCAGGCATCAAATAAAACGAAAGGCTCAGTCGAAAGACTGGGCCTTTCGTTTTATCTGTTG"
              "TTTGTCGGTGAACGCTCTCTACTAGAGTCACACTGGCTCACCTTCGGGTGGGCCTTTCTGC"
              "GTTTATA"),
         provenance="seed — verify vs Registry"),
]


def normalise(seq: str) -> str:
    return "".join(c for c in seq.upper() if c.isalpha())


def _load_fasta(path):
    out, cur, buf = {}, None, []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            if line.startswith(">"):
                if cur:
                    out[cur] = "".join(buf)
                cur = line[1:].strip().split()[0]
                buf = []
            else:
                buf.append(line.strip())
    if cur:
        out[cur] = "".join(buf)
    return out


def _load():
    if not (os.path.exists(_FASTA) and os.path.exists(_TSV)):
        return list(_FALLBACK)
    seqs = _load_fasta(_FASTA)
    parts = []
    with open(_TSV, "r", encoding="utf-8") as f:
        header = f.readline().rstrip("\n").split("\t")
        idx = {h: i for i, h in enumerate(header)}
        for line in f:
            if not line.strip():
                continue
            c = line.rstrip("\n").split("\t")

            def g(k):
                return c[idx[k]] if k in idx and idx[k] < len(c) else ""
            pid = g("id")
            if pid not in seqs:
                continue
            parts.append(dict(
                id=pid, registry=g("registry"), name=g("name"), role=g("role"),
                variant=g("variant") or None, provenance=g("provenance"),
                seq=normalise(seqs[pid]),
            ))
    return parts or list(_FALLBACK)


REFERENCE_PARTS = _load()


# ── user libraries (--library) ──────────────────────────────────────────────

# LOCK records `class`, not role, so role is inferred - conservatively. An id or source that does
# not clearly say what a part IS leaves the role unset: it is still identified by name, and only
# the role-dependent checks sit out. A guessed role runs the wrong check and reports it as fact.
_ROLE_HINTS = (
    ("rbs", ("rbs_", "_rbs", "ribosome binding", "5'utr", "5utr")),
    ("promoter", ("promoter", "p_hrpl", "pyear", "j231")),
    ("terminator", ("terminator", "l3s", "eck120")),
    ("origin", ("_ori", "ori_", "origin", "replicon", "p15a", "psc101", "pmb1", "cole1")),
    ("reporter", ("gfp", "rfp", "cfp", "yfp", "chromoprotein", "amilcp", "lacz", "luc")),
    ("cds", ("cds", "resistance", "kanr", "ampr", "cat ", "operon")),
)


def _infer_role(pid, source):
    hay = f"{pid} {source}".lower()
    for role, needles in _ROLE_HINTS:
        if any(n in hay for n in needles):
            return role
    return ""


def load_katana_library(root):
    """Read a Katana parts library and return (parts, problems).

    `root` is the directory holding LOCK.tsv (normally parts-library/ref_parts). Every part is
    hash-gated exactly as the library gates itself: recompute seq_sha256 from the bytes on disk and
    require it to match BOTH the LOCK row and the 12-hex fingerprint in the filename.
    """
    import hashlib
    import kg_parse

    root = os.path.abspath(root)
    lock = os.path.join(root, "LOCK.tsv")
    if not os.path.isfile(lock):
        return [], [f"no LOCK.tsv in {root}"]

    parts, problems = [], []
    with open(lock, "r", encoding="utf-8") as fh:
        header = fh.readline().rstrip("\n").split("\t")
        idx = {h: i for i, h in enumerate(header)}
        for line in fh:
            if not line.strip():
                continue
            c = line.rstrip("\n").split("\t")

            def g(k):
                return c[idx[k]] if k in idx and idx[k] < len(c) else ""

            pid, outfile = g("id"), g("outfile")
            if not pid or not outfile:
                continue
            path = os.path.join(root, outfile.replace("\\", os.sep).replace("/", os.sep))
            if not os.path.isfile(path):
                problems.append(f"{pid}: {outfile} missing")
                continue
            try:
                seq = normalise(kg_parse.parse(path).seq)
            except Exception as exc:
                problems.append(f"{pid}: unreadable ({exc})")
                continue
            if not seq:
                problems.append(f"{pid}: empty sequence")
                continue

            recomputed = hashlib.sha256(seq.encode()).hexdigest()
            if g("seq_sha256") and recomputed != g("seq_sha256"):
                problems.append(f"{pid}: seq_sha256 {recomputed[:12]} != LOCK {g('seq_sha256')[:12]}")
                continue
            fn12 = os.path.basename(path).rsplit(".", 1)[0].split("__")[-1]
            if len(fn12) == 12 and recomputed[:12] != fn12:
                problems.append(f"{pid}: seq_sha256 {recomputed[:12]} != filename {fn12}")
                continue

            parts.append(dict(
                id=pid, registry="", name=pid, role=_infer_role(pid, g("source")),
                variant=None, seq=seq,
                provenance=f"your library {os.path.basename(path)} "
                           f"[seq_sha256 verified vs LOCK] | {g('source')[:100]}"))
    return parts, problems


def add_library(root):
    """Merge a Katana library into the reference set. Yours wins on an id collision."""
    parts, problems = load_katana_library(root)
    if parts:
        incoming = {p["id"] for p in parts}
        kept = [p for p in REFERENCE_PARTS if p["id"] not in incoming]
        replaced = len(REFERENCE_PARTS) - len(kept)
        REFERENCE_PARTS[:] = kept + parts
        return len(parts), replaced, problems
    return 0, 0, problems



# Provenance tiers, strongest first. Used to break ties between references whose sequences are
# IDENTICAL - fifteen parts carry the exact B0015 sequence, and without this the winner was whichever
# blast happened to list first, so the same construct could be reported with different part names.
_TIERS = (
    ("parts-library", 3),      # re-hashed against LOCK every build
    ("your library", 3),       # --library, same gate
    ("iGEM Registry", 2),      # live, uuid + fetch date
    ("SynBioHub", 1),          # 2017 snapshot, per-part URI
)


def tier(pid, _cache={}):
    """How much we trust this reference's origin. Higher wins a tie."""
    if not _cache:
        for p in REFERENCE_PARTS:
            prov = p.get("provenance") or ""
            _cache[p["id"]] = next((n for pre, n in _TIERS if prov.startswith(pre)), 0)
    return _cache.get(pid, 0)

def by_id():
    return {p["id"]: p for p in REFERENCE_PARTS}
